foreground              #e1e4d9
background              #1d211a
selection_foreground    #d9e7ca
selection_background    #3e4a35

cursor                  #aad290
cursor_text_color       #183806

url_color               #a0cfcf

active_border_color     #aad290
inactive_border_color   #43483e
bell_border_color       #ffb4ab

wayland_titlebar_color  system
macos_titlebar_color    system

active_tab_foreground   #c6efaa
active_tab_background   #2e4f1c
inactive_tab_foreground #c3c8bb
inactive_tab_background #1d211a
tab_bar_background      #11140e

mark1_foreground #183806
mark1_background #aad290
mark2_foreground #283420
mark2_background #bdcbaf
mark3_foreground #003737
mark3_background #a0cfcf

color0 #43483e
color8 #8d9286

color1 #ffb4ab
color9 #93000a

color2  #aad290
color10 #c6efaa

color3  #a0cfcf
color11 #bbebeb

color4  #bdcbaf
color12 #d9e7ca

color5  #2e4f1c
color13 #456731

color6  #3e4a35
color14 #1e4e4e

color7  #c3c8bb
color15 #e1e4d9
