foreground              #e3e1e9
background              #1f1f25
selection_foreground    #dfe1f9
selection_background    #434659

cursor                  #bac3ff
cursor_text_color       #222c61

url_color               #e5bad8

active_border_color     #bac3ff
inactive_border_color   #46464f
bell_border_color       #ffb4ab

wayland_titlebar_color  system
macos_titlebar_color    system

active_tab_foreground   #dee0ff
active_tab_background   #394379
inactive_tab_foreground #c6c5d0
inactive_tab_background #1f1f25
tab_bar_background      #121318

mark1_foreground #222c61
mark1_background #bac3ff
mark2_foreground #2c2f42
mark2_background #c3c5dd
mark3_foreground #44263e
mark3_background #e5bad8

color0 #46464f
color8 #90909a

color1 #ffb4ab
color9 #93000a

color2  #bac3ff
color10 #dee0ff

color3  #e5bad8
color11 #ffd7f2

color4  #c3c5dd
color12 #dfe1f9

color5  #394379
color13 #515b92

color6  #434659
color14 #5d3c55

color7  #c6c5d0
color15 #e3e1e9
