foreground              #e7e2d5
background              #212017
selection_foreground    #eae3bd
selection_background    #4b472c

cursor                  #d3c972
cursor_text_color       #363100

url_color               #a6d0b8

active_border_color     #d3c972
inactive_border_color   #49473a
bell_border_color       #ffb4ab

wayland_titlebar_color  system
macos_titlebar_color    system

active_tab_foreground   #efe58b
active_tab_background   #4e4800
inactive_tab_foreground #cbc7b5
inactive_tab_background #212017
tab_bar_background      #15140c

mark1_foreground #363100
mark1_background #d3c972
mark2_foreground #343117
mark2_background #cdc7a3
mark3_foreground #0f3727
mark3_background #a6d0b8

color0 #49473a
color8 #949181

color1 #ffb4ab
color9 #93000a

color2  #d3c972
color10 #efe58b

color3  #a6d0b8
color11 #c2ecd4

color4  #cdc7a3
color12 #eae3bd

color5  #4e4800
color13 #676013

color6  #4b472c
color14 #284e3c

color7  #cbc7b5
color15 #e7e2d5
