font_family      Maple Mono NF Bold
font_size        16.0
bold_font        auto
italic_font      auto
bold_italic_font auto

cursor_trail 1

background_opacity 0.75
background_blur_radius 40
confirm_os_window_close 0

scrollback_lines 2000
wheel_scroll_min_lines 1

enable_audio_bell no
hide_window_decorations yes

window_padding_width 4

url_prefixes https:// http:// ftp://
open_url_with xdg-open
shell_integration enabled

map ctrl+shift+e open_url_with_hints

include ~/.config/kitty/colors.conf

